stages:
  - test
  - pages



# run tests using the binary built before
test:
  image: gcc
  stage: test
  before_script:
    - apt update && apt -y install ninja-build cmake
  script:
    - cmake -G "Ninja" -B build
    - cmake --build build --target all
  cache:
      paths:
        - build/

pages:
  image: alpine
  script:
  - apk update && apk add doxygen graphviz ttf-freefont
  - doxygen docs/doxygen.conf
  - mv docs/html/ public/
  artifacts:
    paths:
    - public
  only:
  - main