name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: lukka/get-cmake@v3.30.0
      
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset default

      - name: Build tests
        run: cmake --build --preset testing

      - name: Test
        run: ctest --preset default

      - name: Install
        run: cmake --build --preset install
