name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: lukka/get-cmake@v3.30.0
      
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset default

      - name: Build tests
        run: cmake --build --preset testing

      - name: Test
        run: ctest --preset default

      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/tests/CMakeFiles/*.gcda
          
      - name: Install
        run: cmake --build --preset install
