name: Update latest tag

on:
  release:
    types:
      - released
      - edited

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: EndBug/latest-tag@latest
